spring:
  application:
    name: hrmex

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hrmex_db
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.fullstack: DEBUG